title: Autonomous Discovery of Alloys (AutoDIAL)
description: Department of Materials Science and Engineering, University of Toronto
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

# Social media preview image
image: /assets/images/nulla_bw.png
logo: /assets/images/nulla_bw.png

# Collections configuration
collections:
  news:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

plugins:
  - jekyll-feed